### ISSUE TITLE
import setttings

### ISSUE THREAD

**Issue by BlastPy** [micrypt/django-valuate#1]
/home/blast/blog/local/lib/python2.7/site-packages/django_valuate-1.0_beta_2.3-py2.7.egg/valuate/models.py:4: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/blast/blog/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/blast/blog/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 312, in execute
    django.setup()
  File "/home/blast/blog/local/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/blast/blog/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/blast/blog/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/blast/blog/local/lib/python2.7/site-packages/django_valuate-1.0_beta_2.3-py2.7.egg/valuate/models.py", line 8, in <module>
    from valuate.managers import ValuationManager, ValuationTypeManager
  File "/home/blast/blog/local/lib/python2.7/site-packages/django_valuate-1.0_beta_2.3-py2.7.egg/valuate/managers.py", line 4, in <module>
    import settings
ImportError: No module named settings

**Comment by micrypt** [comment]
So, I expect you are using a recent release of Django. This package hasn't been updated in a few years, but the correct import path for settings is now `django.conf.settings`. I've updated this, but can imagine there are a few other issues that would require fixing to make this work smoothly with the current Django release. I haven't had time to deal with maintenance of late, but should be able to in the coming months. Of course, pull requests are welcome.
